// Generated by gencpp from file dobot/ClearAllAlarmsState.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_CLEARALLALARMSSTATE_H
#define DOBOT_MESSAGE_CLEARALLALARMSSTATE_H

#include <ros/service_traits.h>


#include <dobot/ClearAllAlarmsStateRequest.h>
#include <dobot/ClearAllAlarmsStateResponse.h>


namespace dobot
{

struct ClearAllAlarmsState
{

typedef ClearAllAlarmsStateRequest Request;
typedef ClearAllAlarmsStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ClearAllAlarmsState
} // namespace dobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot::ClearAllAlarmsState > {
  static const char* value()
  {
    return "034a8e20d6a306665e3a5b340fab3f09";
  }

  static const char* value(const ::dobot::ClearAllAlarmsState&) { return value(); }
};

template<>
struct DataType< ::dobot::ClearAllAlarmsState > {
  static const char* value()
  {
    return "dobot/ClearAllAlarmsState";
  }

  static const char* value(const ::dobot::ClearAllAlarmsState&) { return value(); }
};


// service_traits::MD5Sum< ::dobot::ClearAllAlarmsStateRequest> should match 
// service_traits::MD5Sum< ::dobot::ClearAllAlarmsState > 
template<>
struct MD5Sum< ::dobot::ClearAllAlarmsStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::ClearAllAlarmsState >::value();
  }
  static const char* value(const ::dobot::ClearAllAlarmsStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::ClearAllAlarmsStateRequest> should match 
// service_traits::DataType< ::dobot::ClearAllAlarmsState > 
template<>
struct DataType< ::dobot::ClearAllAlarmsStateRequest>
{
  static const char* value()
  {
    return DataType< ::dobot::ClearAllAlarmsState >::value();
  }
  static const char* value(const ::dobot::ClearAllAlarmsStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot::ClearAllAlarmsStateResponse> should match 
// service_traits::MD5Sum< ::dobot::ClearAllAlarmsState > 
template<>
struct MD5Sum< ::dobot::ClearAllAlarmsStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::ClearAllAlarmsState >::value();
  }
  static const char* value(const ::dobot::ClearAllAlarmsStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::ClearAllAlarmsStateResponse> should match 
// service_traits::DataType< ::dobot::ClearAllAlarmsState > 
template<>
struct DataType< ::dobot::ClearAllAlarmsStateResponse>
{
  static const char* value()
  {
    return DataType< ::dobot::ClearAllAlarmsState >::value();
  }
  static const char* value(const ::dobot::ClearAllAlarmsStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_MESSAGE_CLEARALLALARMSSTATE_H
