// Generated by gencpp from file dobot/GetARCParams.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_GETARCPARAMS_H
#define DOBOT_MESSAGE_GETARCPARAMS_H

#include <ros/service_traits.h>


#include <dobot/GetARCParamsRequest.h>
#include <dobot/GetARCParamsResponse.h>


namespace dobot
{

struct GetARCParams
{

typedef GetARCParamsRequest Request;
typedef GetARCParamsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetARCParams
} // namespace dobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot::GetARCParams > {
  static const char* value()
  {
    return "886db9a7d126004f299ba6b6878cb966";
  }

  static const char* value(const ::dobot::GetARCParams&) { return value(); }
};

template<>
struct DataType< ::dobot::GetARCParams > {
  static const char* value()
  {
    return "dobot/GetARCParams";
  }

  static const char* value(const ::dobot::GetARCParams&) { return value(); }
};


// service_traits::MD5Sum< ::dobot::GetARCParamsRequest> should match 
// service_traits::MD5Sum< ::dobot::GetARCParams > 
template<>
struct MD5Sum< ::dobot::GetARCParamsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::GetARCParams >::value();
  }
  static const char* value(const ::dobot::GetARCParamsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::GetARCParamsRequest> should match 
// service_traits::DataType< ::dobot::GetARCParams > 
template<>
struct DataType< ::dobot::GetARCParamsRequest>
{
  static const char* value()
  {
    return DataType< ::dobot::GetARCParams >::value();
  }
  static const char* value(const ::dobot::GetARCParamsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot::GetARCParamsResponse> should match 
// service_traits::MD5Sum< ::dobot::GetARCParams > 
template<>
struct MD5Sum< ::dobot::GetARCParamsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::GetARCParams >::value();
  }
  static const char* value(const ::dobot::GetARCParamsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::GetARCParamsResponse> should match 
// service_traits::DataType< ::dobot::GetARCParams > 
template<>
struct DataType< ::dobot::GetARCParamsResponse>
{
  static const char* value()
  {
    return DataType< ::dobot::GetARCParams >::value();
  }
  static const char* value(const ::dobot::GetARCParamsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_MESSAGE_GETARCPARAMS_H
