// Generated by gencpp from file dobot/GetCPParams.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_GETCPPARAMS_H
#define DOBOT_MESSAGE_GETCPPARAMS_H

#include <ros/service_traits.h>


#include <dobot/GetCPParamsRequest.h>
#include <dobot/GetCPParamsResponse.h>


namespace dobot
{

struct GetCPParams
{

typedef GetCPParamsRequest Request;
typedef GetCPParamsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetCPParams
} // namespace dobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot::GetCPParams > {
  static const char* value()
  {
    return "85dff81a44afbb98d15e48705b4ea806";
  }

  static const char* value(const ::dobot::GetCPParams&) { return value(); }
};

template<>
struct DataType< ::dobot::GetCPParams > {
  static const char* value()
  {
    return "dobot/GetCPParams";
  }

  static const char* value(const ::dobot::GetCPParams&) { return value(); }
};


// service_traits::MD5Sum< ::dobot::GetCPParamsRequest> should match 
// service_traits::MD5Sum< ::dobot::GetCPParams > 
template<>
struct MD5Sum< ::dobot::GetCPParamsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::GetCPParams >::value();
  }
  static const char* value(const ::dobot::GetCPParamsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::GetCPParamsRequest> should match 
// service_traits::DataType< ::dobot::GetCPParams > 
template<>
struct DataType< ::dobot::GetCPParamsRequest>
{
  static const char* value()
  {
    return DataType< ::dobot::GetCPParams >::value();
  }
  static const char* value(const ::dobot::GetCPParamsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot::GetCPParamsResponse> should match 
// service_traits::MD5Sum< ::dobot::GetCPParams > 
template<>
struct MD5Sum< ::dobot::GetCPParamsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::GetCPParams >::value();
  }
  static const char* value(const ::dobot::GetCPParamsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::GetCPParamsResponse> should match 
// service_traits::DataType< ::dobot::GetCPParams > 
template<>
struct DataType< ::dobot::GetCPParamsResponse>
{
  static const char* value()
  {
    return DataType< ::dobot::GetCPParams >::value();
  }
  static const char* value(const ::dobot::GetCPParamsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_MESSAGE_GETCPPARAMS_H
