// Generated by gencpp from file dobot/GetDeviceSN.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_GETDEVICESN_H
#define DOBOT_MESSAGE_GETDEVICESN_H

#include <ros/service_traits.h>


#include <dobot/GetDeviceSNRequest.h>
#include <dobot/GetDeviceSNResponse.h>


namespace dobot
{

struct GetDeviceSN
{

typedef GetDeviceSNRequest Request;
typedef GetDeviceSNResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetDeviceSN
} // namespace dobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot::GetDeviceSN > {
  static const char* value()
  {
    return "e0f9486ebe760ac95403f1a902002a01";
  }

  static const char* value(const ::dobot::GetDeviceSN&) { return value(); }
};

template<>
struct DataType< ::dobot::GetDeviceSN > {
  static const char* value()
  {
    return "dobot/GetDeviceSN";
  }

  static const char* value(const ::dobot::GetDeviceSN&) { return value(); }
};


// service_traits::MD5Sum< ::dobot::GetDeviceSNRequest> should match 
// service_traits::MD5Sum< ::dobot::GetDeviceSN > 
template<>
struct MD5Sum< ::dobot::GetDeviceSNRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::GetDeviceSN >::value();
  }
  static const char* value(const ::dobot::GetDeviceSNRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::GetDeviceSNRequest> should match 
// service_traits::DataType< ::dobot::GetDeviceSN > 
template<>
struct DataType< ::dobot::GetDeviceSNRequest>
{
  static const char* value()
  {
    return DataType< ::dobot::GetDeviceSN >::value();
  }
  static const char* value(const ::dobot::GetDeviceSNRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot::GetDeviceSNResponse> should match 
// service_traits::MD5Sum< ::dobot::GetDeviceSN > 
template<>
struct MD5Sum< ::dobot::GetDeviceSNResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::GetDeviceSN >::value();
  }
  static const char* value(const ::dobot::GetDeviceSNResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::GetDeviceSNResponse> should match 
// service_traits::DataType< ::dobot::GetDeviceSN > 
template<>
struct DataType< ::dobot::GetDeviceSNResponse>
{
  static const char* value()
  {
    return DataType< ::dobot::GetDeviceSN >::value();
  }
  static const char* value(const ::dobot::GetDeviceSNResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_MESSAGE_GETDEVICESN_H
