// Generated by gencpp from file dobot/GetEndEffectorSuctionCup.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_GETENDEFFECTORSUCTIONCUP_H
#define DOBOT_MESSAGE_GETENDEFFECTORSUCTIONCUP_H

#include <ros/service_traits.h>


#include <dobot/GetEndEffectorSuctionCupRequest.h>
#include <dobot/GetEndEffectorSuctionCupResponse.h>


namespace dobot
{

struct GetEndEffectorSuctionCup
{

typedef GetEndEffectorSuctionCupRequest Request;
typedef GetEndEffectorSuctionCupResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetEndEffectorSuctionCup
} // namespace dobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot::GetEndEffectorSuctionCup > {
  static const char* value()
  {
    return "4855d73076b6df7c6c4785878f4cef46";
  }

  static const char* value(const ::dobot::GetEndEffectorSuctionCup&) { return value(); }
};

template<>
struct DataType< ::dobot::GetEndEffectorSuctionCup > {
  static const char* value()
  {
    return "dobot/GetEndEffectorSuctionCup";
  }

  static const char* value(const ::dobot::GetEndEffectorSuctionCup&) { return value(); }
};


// service_traits::MD5Sum< ::dobot::GetEndEffectorSuctionCupRequest> should match 
// service_traits::MD5Sum< ::dobot::GetEndEffectorSuctionCup > 
template<>
struct MD5Sum< ::dobot::GetEndEffectorSuctionCupRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::GetEndEffectorSuctionCup >::value();
  }
  static const char* value(const ::dobot::GetEndEffectorSuctionCupRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::GetEndEffectorSuctionCupRequest> should match 
// service_traits::DataType< ::dobot::GetEndEffectorSuctionCup > 
template<>
struct DataType< ::dobot::GetEndEffectorSuctionCupRequest>
{
  static const char* value()
  {
    return DataType< ::dobot::GetEndEffectorSuctionCup >::value();
  }
  static const char* value(const ::dobot::GetEndEffectorSuctionCupRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot::GetEndEffectorSuctionCupResponse> should match 
// service_traits::MD5Sum< ::dobot::GetEndEffectorSuctionCup > 
template<>
struct MD5Sum< ::dobot::GetEndEffectorSuctionCupResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::GetEndEffectorSuctionCup >::value();
  }
  static const char* value(const ::dobot::GetEndEffectorSuctionCupResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::GetEndEffectorSuctionCupResponse> should match 
// service_traits::DataType< ::dobot::GetEndEffectorSuctionCup > 
template<>
struct DataType< ::dobot::GetEndEffectorSuctionCupResponse>
{
  static const char* value()
  {
    return DataType< ::dobot::GetEndEffectorSuctionCup >::value();
  }
  static const char* value(const ::dobot::GetEndEffectorSuctionCupResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_MESSAGE_GETENDEFFECTORSUCTIONCUP_H
