// Generated by gencpp from file dobot/GetEndEffectorParams.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_GETENDEFFECTORPARAMS_H
#define DOBOT_MESSAGE_GETENDEFFECTORPARAMS_H

#include <ros/service_traits.h>


#include <dobot/GetEndEffectorParamsRequest.h>
#include <dobot/GetEndEffectorParamsResponse.h>


namespace dobot
{

struct GetEndEffectorParams
{

typedef GetEndEffectorParamsRequest Request;
typedef GetEndEffectorParamsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetEndEffectorParams
} // namespace dobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot::GetEndEffectorParams > {
  static const char* value()
  {
    return "a07055f2964cf165e2fb447024254f9f";
  }

  static const char* value(const ::dobot::GetEndEffectorParams&) { return value(); }
};

template<>
struct DataType< ::dobot::GetEndEffectorParams > {
  static const char* value()
  {
    return "dobot/GetEndEffectorParams";
  }

  static const char* value(const ::dobot::GetEndEffectorParams&) { return value(); }
};


// service_traits::MD5Sum< ::dobot::GetEndEffectorParamsRequest> should match 
// service_traits::MD5Sum< ::dobot::GetEndEffectorParams > 
template<>
struct MD5Sum< ::dobot::GetEndEffectorParamsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::GetEndEffectorParams >::value();
  }
  static const char* value(const ::dobot::GetEndEffectorParamsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::GetEndEffectorParamsRequest> should match 
// service_traits::DataType< ::dobot::GetEndEffectorParams > 
template<>
struct DataType< ::dobot::GetEndEffectorParamsRequest>
{
  static const char* value()
  {
    return DataType< ::dobot::GetEndEffectorParams >::value();
  }
  static const char* value(const ::dobot::GetEndEffectorParamsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot::GetEndEffectorParamsResponse> should match 
// service_traits::MD5Sum< ::dobot::GetEndEffectorParams > 
template<>
struct MD5Sum< ::dobot::GetEndEffectorParamsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::GetEndEffectorParams >::value();
  }
  static const char* value(const ::dobot::GetEndEffectorParamsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::GetEndEffectorParamsResponse> should match 
// service_traits::DataType< ::dobot::GetEndEffectorParams > 
template<>
struct DataType< ::dobot::GetEndEffectorParamsResponse>
{
  static const char* value()
  {
    return DataType< ::dobot::GetEndEffectorParams >::value();
  }
  static const char* value(const ::dobot::GetEndEffectorParamsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_MESSAGE_GETENDEFFECTORPARAMS_H
