// Generated by gencpp from file dobot/GetIOPWM.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_GETIOPWM_H
#define DOBOT_MESSAGE_GETIOPWM_H

#include <ros/service_traits.h>


#include <dobot/GetIOPWMRequest.h>
#include <dobot/GetIOPWMResponse.h>


namespace dobot
{

struct GetIOPWM
{

typedef GetIOPWMRequest Request;
typedef GetIOPWMResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetIOPWM
} // namespace dobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot::GetIOPWM > {
  static const char* value()
  {
    return "e74ebc842c028d734a6d61feb93c5a53";
  }

  static const char* value(const ::dobot::GetIOPWM&) { return value(); }
};

template<>
struct DataType< ::dobot::GetIOPWM > {
  static const char* value()
  {
    return "dobot/GetIOPWM";
  }

  static const char* value(const ::dobot::GetIOPWM&) { return value(); }
};


// service_traits::MD5Sum< ::dobot::GetIOPWMRequest> should match 
// service_traits::MD5Sum< ::dobot::GetIOPWM > 
template<>
struct MD5Sum< ::dobot::GetIOPWMRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::GetIOPWM >::value();
  }
  static const char* value(const ::dobot::GetIOPWMRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::GetIOPWMRequest> should match 
// service_traits::DataType< ::dobot::GetIOPWM > 
template<>
struct DataType< ::dobot::GetIOPWMRequest>
{
  static const char* value()
  {
    return DataType< ::dobot::GetIOPWM >::value();
  }
  static const char* value(const ::dobot::GetIOPWMRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot::GetIOPWMResponse> should match 
// service_traits::MD5Sum< ::dobot::GetIOPWM > 
template<>
struct MD5Sum< ::dobot::GetIOPWMResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::GetIOPWM >::value();
  }
  static const char* value(const ::dobot::GetIOPWMResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::GetIOPWMResponse> should match 
// service_traits::DataType< ::dobot::GetIOPWM > 
template<>
struct DataType< ::dobot::GetIOPWMResponse>
{
  static const char* value()
  {
    return DataType< ::dobot::GetIOPWM >::value();
  }
  static const char* value(const ::dobot::GetIOPWMResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_MESSAGE_GETIOPWM_H
