// Generated by gencpp from file dobot/GetJOGCommonParams.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_GETJOGCOMMONPARAMS_H
#define DOBOT_MESSAGE_GETJOGCOMMONPARAMS_H

#include <ros/service_traits.h>


#include <dobot/GetJOGCommonParamsRequest.h>
#include <dobot/GetJOGCommonParamsResponse.h>


namespace dobot
{

struct GetJOGCommonParams
{

typedef GetJOGCommonParamsRequest Request;
typedef GetJOGCommonParamsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetJOGCommonParams
} // namespace dobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot::GetJOGCommonParams > {
  static const char* value()
  {
    return "ccb42558fae0625dedee5118e81add9a";
  }

  static const char* value(const ::dobot::GetJOGCommonParams&) { return value(); }
};

template<>
struct DataType< ::dobot::GetJOGCommonParams > {
  static const char* value()
  {
    return "dobot/GetJOGCommonParams";
  }

  static const char* value(const ::dobot::GetJOGCommonParams&) { return value(); }
};


// service_traits::MD5Sum< ::dobot::GetJOGCommonParamsRequest> should match 
// service_traits::MD5Sum< ::dobot::GetJOGCommonParams > 
template<>
struct MD5Sum< ::dobot::GetJOGCommonParamsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::GetJOGCommonParams >::value();
  }
  static const char* value(const ::dobot::GetJOGCommonParamsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::GetJOGCommonParamsRequest> should match 
// service_traits::DataType< ::dobot::GetJOGCommonParams > 
template<>
struct DataType< ::dobot::GetJOGCommonParamsRequest>
{
  static const char* value()
  {
    return DataType< ::dobot::GetJOGCommonParams >::value();
  }
  static const char* value(const ::dobot::GetJOGCommonParamsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot::GetJOGCommonParamsResponse> should match 
// service_traits::MD5Sum< ::dobot::GetJOGCommonParams > 
template<>
struct MD5Sum< ::dobot::GetJOGCommonParamsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::GetJOGCommonParams >::value();
  }
  static const char* value(const ::dobot::GetJOGCommonParamsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::GetJOGCommonParamsResponse> should match 
// service_traits::DataType< ::dobot::GetJOGCommonParams > 
template<>
struct DataType< ::dobot::GetJOGCommonParamsResponse>
{
  static const char* value()
  {
    return DataType< ::dobot::GetJOGCommonParams >::value();
  }
  static const char* value(const ::dobot::GetJOGCommonParamsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_MESSAGE_GETJOGCOMMONPARAMS_H
