// Generated by gencpp from file dobot/GetPTPJumpParams.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_GETPTPJUMPPARAMS_H
#define DOBOT_MESSAGE_GETPTPJUMPPARAMS_H

#include <ros/service_traits.h>


#include <dobot/GetPTPJumpParamsRequest.h>
#include <dobot/GetPTPJumpParamsResponse.h>


namespace dobot
{

struct GetPTPJumpParams
{

typedef GetPTPJumpParamsRequest Request;
typedef GetPTPJumpParamsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPTPJumpParams
} // namespace dobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot::GetPTPJumpParams > {
  static const char* value()
  {
    return "c789ca108051f9c81e48ec0ed44d3ab7";
  }

  static const char* value(const ::dobot::GetPTPJumpParams&) { return value(); }
};

template<>
struct DataType< ::dobot::GetPTPJumpParams > {
  static const char* value()
  {
    return "dobot/GetPTPJumpParams";
  }

  static const char* value(const ::dobot::GetPTPJumpParams&) { return value(); }
};


// service_traits::MD5Sum< ::dobot::GetPTPJumpParamsRequest> should match 
// service_traits::MD5Sum< ::dobot::GetPTPJumpParams > 
template<>
struct MD5Sum< ::dobot::GetPTPJumpParamsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::GetPTPJumpParams >::value();
  }
  static const char* value(const ::dobot::GetPTPJumpParamsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::GetPTPJumpParamsRequest> should match 
// service_traits::DataType< ::dobot::GetPTPJumpParams > 
template<>
struct DataType< ::dobot::GetPTPJumpParamsRequest>
{
  static const char* value()
  {
    return DataType< ::dobot::GetPTPJumpParams >::value();
  }
  static const char* value(const ::dobot::GetPTPJumpParamsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot::GetPTPJumpParamsResponse> should match 
// service_traits::MD5Sum< ::dobot::GetPTPJumpParams > 
template<>
struct MD5Sum< ::dobot::GetPTPJumpParamsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::GetPTPJumpParams >::value();
  }
  static const char* value(const ::dobot::GetPTPJumpParamsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::GetPTPJumpParamsResponse> should match 
// service_traits::DataType< ::dobot::GetPTPJumpParams > 
template<>
struct DataType< ::dobot::GetPTPJumpParamsResponse>
{
  static const char* value()
  {
    return DataType< ::dobot::GetPTPJumpParams >::value();
  }
  static const char* value(const ::dobot::GetPTPJumpParamsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_MESSAGE_GETPTPJUMPPARAMS_H
