// Generated by gencpp from file dobot/GetPTPCoordinateParams.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_GETPTPCOORDINATEPARAMS_H
#define DOBOT_MESSAGE_GETPTPCOORDINATEPARAMS_H

#include <ros/service_traits.h>


#include <dobot/GetPTPCoordinateParamsRequest.h>
#include <dobot/GetPTPCoordinateParamsResponse.h>


namespace dobot
{

struct GetPTPCoordinateParams
{

typedef GetPTPCoordinateParamsRequest Request;
typedef GetPTPCoordinateParamsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPTPCoordinateParams
} // namespace dobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot::GetPTPCoordinateParams > {
  static const char* value()
  {
    return "886db9a7d126004f299ba6b6878cb966";
  }

  static const char* value(const ::dobot::GetPTPCoordinateParams&) { return value(); }
};

template<>
struct DataType< ::dobot::GetPTPCoordinateParams > {
  static const char* value()
  {
    return "dobot/GetPTPCoordinateParams";
  }

  static const char* value(const ::dobot::GetPTPCoordinateParams&) { return value(); }
};


// service_traits::MD5Sum< ::dobot::GetPTPCoordinateParamsRequest> should match 
// service_traits::MD5Sum< ::dobot::GetPTPCoordinateParams > 
template<>
struct MD5Sum< ::dobot::GetPTPCoordinateParamsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::GetPTPCoordinateParams >::value();
  }
  static const char* value(const ::dobot::GetPTPCoordinateParamsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::GetPTPCoordinateParamsRequest> should match 
// service_traits::DataType< ::dobot::GetPTPCoordinateParams > 
template<>
struct DataType< ::dobot::GetPTPCoordinateParamsRequest>
{
  static const char* value()
  {
    return DataType< ::dobot::GetPTPCoordinateParams >::value();
  }
  static const char* value(const ::dobot::GetPTPCoordinateParamsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot::GetPTPCoordinateParamsResponse> should match 
// service_traits::MD5Sum< ::dobot::GetPTPCoordinateParams > 
template<>
struct MD5Sum< ::dobot::GetPTPCoordinateParamsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::GetPTPCoordinateParams >::value();
  }
  static const char* value(const ::dobot::GetPTPCoordinateParamsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::GetPTPCoordinateParamsResponse> should match 
// service_traits::DataType< ::dobot::GetPTPCoordinateParams > 
template<>
struct DataType< ::dobot::GetPTPCoordinateParamsResponse>
{
  static const char* value()
  {
    return DataType< ::dobot::GetPTPCoordinateParams >::value();
  }
  static const char* value(const ::dobot::GetPTPCoordinateParamsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_MESSAGE_GETPTPCOORDINATEPARAMS_H
