// Generated by gencpp from file dobot/GetPose.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_GETPOSE_H
#define DOBOT_MESSAGE_GETPOSE_H

#include <ros/service_traits.h>


#include <dobot/GetPoseRequest.h>
#include <dobot/GetPoseResponse.h>


namespace dobot
{

struct GetPose
{

typedef GetPoseRequest Request;
typedef GetPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPose
} // namespace dobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot::GetPose > {
  static const char* value()
  {
    return "d4de75e47bb9a51cbb33e89d50edf04f";
  }

  static const char* value(const ::dobot::GetPose&) { return value(); }
};

template<>
struct DataType< ::dobot::GetPose > {
  static const char* value()
  {
    return "dobot/GetPose";
  }

  static const char* value(const ::dobot::GetPose&) { return value(); }
};


// service_traits::MD5Sum< ::dobot::GetPoseRequest> should match 
// service_traits::MD5Sum< ::dobot::GetPose > 
template<>
struct MD5Sum< ::dobot::GetPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::GetPose >::value();
  }
  static const char* value(const ::dobot::GetPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::GetPoseRequest> should match 
// service_traits::DataType< ::dobot::GetPose > 
template<>
struct DataType< ::dobot::GetPoseRequest>
{
  static const char* value()
  {
    return DataType< ::dobot::GetPose >::value();
  }
  static const char* value(const ::dobot::GetPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot::GetPoseResponse> should match 
// service_traits::MD5Sum< ::dobot::GetPose > 
template<>
struct MD5Sum< ::dobot::GetPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::GetPose >::value();
  }
  static const char* value(const ::dobot::GetPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::GetPoseResponse> should match 
// service_traits::DataType< ::dobot::GetPose > 
template<>
struct DataType< ::dobot::GetPoseResponse>
{
  static const char* value()
  {
    return DataType< ::dobot::GetPose >::value();
  }
  static const char* value(const ::dobot::GetPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_MESSAGE_GETPOSE_H
