// Generated by gencpp from file dobot/SetARCParams.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_SETARCPARAMS_H
#define DOBOT_MESSAGE_SETARCPARAMS_H

#include <ros/service_traits.h>


#include <dobot/SetARCParamsRequest.h>
#include <dobot/SetARCParamsResponse.h>


namespace dobot
{

struct SetARCParams
{

typedef SetARCParamsRequest Request;
typedef SetARCParamsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetARCParams
} // namespace dobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot::SetARCParams > {
  static const char* value()
  {
    return "667693b23f3c212883d158fa88cec8f5";
  }

  static const char* value(const ::dobot::SetARCParams&) { return value(); }
};

template<>
struct DataType< ::dobot::SetARCParams > {
  static const char* value()
  {
    return "dobot/SetARCParams";
  }

  static const char* value(const ::dobot::SetARCParams&) { return value(); }
};


// service_traits::MD5Sum< ::dobot::SetARCParamsRequest> should match 
// service_traits::MD5Sum< ::dobot::SetARCParams > 
template<>
struct MD5Sum< ::dobot::SetARCParamsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::SetARCParams >::value();
  }
  static const char* value(const ::dobot::SetARCParamsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::SetARCParamsRequest> should match 
// service_traits::DataType< ::dobot::SetARCParams > 
template<>
struct DataType< ::dobot::SetARCParamsRequest>
{
  static const char* value()
  {
    return DataType< ::dobot::SetARCParams >::value();
  }
  static const char* value(const ::dobot::SetARCParamsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot::SetARCParamsResponse> should match 
// service_traits::MD5Sum< ::dobot::SetARCParams > 
template<>
struct MD5Sum< ::dobot::SetARCParamsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::SetARCParams >::value();
  }
  static const char* value(const ::dobot::SetARCParamsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::SetARCParamsResponse> should match 
// service_traits::DataType< ::dobot::SetARCParams > 
template<>
struct DataType< ::dobot::SetARCParamsResponse>
{
  static const char* value()
  {
    return DataType< ::dobot::SetARCParams >::value();
  }
  static const char* value(const ::dobot::SetARCParamsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_MESSAGE_SETARCPARAMS_H
