// Generated by gencpp from file dobot/SetARCCmd.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_SETARCCMD_H
#define DOBOT_MESSAGE_SETARCCMD_H

#include <ros/service_traits.h>


#include <dobot/SetARCCmdRequest.h>
#include <dobot/SetARCCmdResponse.h>


namespace dobot
{

struct SetARCCmd
{

typedef SetARCCmdRequest Request;
typedef SetARCCmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetARCCmd
} // namespace dobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot::SetARCCmd > {
  static const char* value()
  {
    return "6b277c29ebdf53b160a46c83993b3c02";
  }

  static const char* value(const ::dobot::SetARCCmd&) { return value(); }
};

template<>
struct DataType< ::dobot::SetARCCmd > {
  static const char* value()
  {
    return "dobot/SetARCCmd";
  }

  static const char* value(const ::dobot::SetARCCmd&) { return value(); }
};


// service_traits::MD5Sum< ::dobot::SetARCCmdRequest> should match 
// service_traits::MD5Sum< ::dobot::SetARCCmd > 
template<>
struct MD5Sum< ::dobot::SetARCCmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::SetARCCmd >::value();
  }
  static const char* value(const ::dobot::SetARCCmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::SetARCCmdRequest> should match 
// service_traits::DataType< ::dobot::SetARCCmd > 
template<>
struct DataType< ::dobot::SetARCCmdRequest>
{
  static const char* value()
  {
    return DataType< ::dobot::SetARCCmd >::value();
  }
  static const char* value(const ::dobot::SetARCCmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot::SetARCCmdResponse> should match 
// service_traits::MD5Sum< ::dobot::SetARCCmd > 
template<>
struct MD5Sum< ::dobot::SetARCCmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::SetARCCmd >::value();
  }
  static const char* value(const ::dobot::SetARCCmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::SetARCCmdResponse> should match 
// service_traits::DataType< ::dobot::SetARCCmd > 
template<>
struct DataType< ::dobot::SetARCCmdResponse>
{
  static const char* value()
  {
    return DataType< ::dobot::SetARCCmd >::value();
  }
  static const char* value(const ::dobot::SetARCCmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_MESSAGE_SETARCCMD_H
