// Generated by gencpp from file dobot/SetCmdTimeoutRequest.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_SETCMDTIMEOUTREQUEST_H
#define DOBOT_MESSAGE_SETCMDTIMEOUTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot
{
template <class ContainerAllocator>
struct SetCmdTimeoutRequest_
{
  typedef SetCmdTimeoutRequest_<ContainerAllocator> Type;

  SetCmdTimeoutRequest_()
    : timeout(0)  {
    }
  SetCmdTimeoutRequest_(const ContainerAllocator& _alloc)
    : timeout(0)  {
  (void)_alloc;
    }



   typedef uint32_t _timeout_type;
  _timeout_type timeout;




  typedef boost::shared_ptr< ::dobot::SetCmdTimeoutRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot::SetCmdTimeoutRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetCmdTimeoutRequest_

typedef ::dobot::SetCmdTimeoutRequest_<std::allocator<void> > SetCmdTimeoutRequest;

typedef boost::shared_ptr< ::dobot::SetCmdTimeoutRequest > SetCmdTimeoutRequestPtr;
typedef boost::shared_ptr< ::dobot::SetCmdTimeoutRequest const> SetCmdTimeoutRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot::SetCmdTimeoutRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot::SetCmdTimeoutRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dobot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'dobot': ['/home/qch/dobot_ws/src/dobot/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dobot::SetCmdTimeoutRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot::SetCmdTimeoutRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::SetCmdTimeoutRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::SetCmdTimeoutRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::SetCmdTimeoutRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::SetCmdTimeoutRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot::SetCmdTimeoutRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "971faa53b2e2e970811208c17e1880c5";
  }

  static const char* value(const ::dobot::SetCmdTimeoutRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x971faa53b2e2e970ULL;
  static const uint64_t static_value2 = 0x811208c17e1880c5ULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot::SetCmdTimeoutRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot/SetCmdTimeoutRequest";
  }

  static const char* value(const ::dobot::SetCmdTimeoutRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot::SetCmdTimeoutRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 timeout\n\
";
  }

  static const char* value(const ::dobot::SetCmdTimeoutRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot::SetCmdTimeoutRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timeout);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetCmdTimeoutRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot::SetCmdTimeoutRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot::SetCmdTimeoutRequest_<ContainerAllocator>& v)
  {
    s << indent << "timeout: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.timeout);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_MESSAGE_SETCMDTIMEOUTREQUEST_H
