// Generated by gencpp from file dobot/SetCmdTimeout.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_SETCMDTIMEOUT_H
#define DOBOT_MESSAGE_SETCMDTIMEOUT_H

#include <ros/service_traits.h>


#include <dobot/SetCmdTimeoutRequest.h>
#include <dobot/SetCmdTimeoutResponse.h>


namespace dobot
{

struct SetCmdTimeout
{

typedef SetCmdTimeoutRequest Request;
typedef SetCmdTimeoutResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetCmdTimeout
} // namespace dobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot::SetCmdTimeout > {
  static const char* value()
  {
    return "13441e7d88f3c6f438486b7bab0cc968";
  }

  static const char* value(const ::dobot::SetCmdTimeout&) { return value(); }
};

template<>
struct DataType< ::dobot::SetCmdTimeout > {
  static const char* value()
  {
    return "dobot/SetCmdTimeout";
  }

  static const char* value(const ::dobot::SetCmdTimeout&) { return value(); }
};


// service_traits::MD5Sum< ::dobot::SetCmdTimeoutRequest> should match 
// service_traits::MD5Sum< ::dobot::SetCmdTimeout > 
template<>
struct MD5Sum< ::dobot::SetCmdTimeoutRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::SetCmdTimeout >::value();
  }
  static const char* value(const ::dobot::SetCmdTimeoutRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::SetCmdTimeoutRequest> should match 
// service_traits::DataType< ::dobot::SetCmdTimeout > 
template<>
struct DataType< ::dobot::SetCmdTimeoutRequest>
{
  static const char* value()
  {
    return DataType< ::dobot::SetCmdTimeout >::value();
  }
  static const char* value(const ::dobot::SetCmdTimeoutRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot::SetCmdTimeoutResponse> should match 
// service_traits::MD5Sum< ::dobot::SetCmdTimeout > 
template<>
struct MD5Sum< ::dobot::SetCmdTimeoutResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::SetCmdTimeout >::value();
  }
  static const char* value(const ::dobot::SetCmdTimeoutResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::SetCmdTimeoutResponse> should match 
// service_traits::DataType< ::dobot::SetCmdTimeout > 
template<>
struct DataType< ::dobot::SetCmdTimeoutResponse>
{
  static const char* value()
  {
    return DataType< ::dobot::SetCmdTimeout >::value();
  }
  static const char* value(const ::dobot::SetCmdTimeoutResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_MESSAGE_SETCMDTIMEOUT_H
