// Generated by gencpp from file dobot/SetEndEffectorSuctionCup.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_SETENDEFFECTORSUCTIONCUP_H
#define DOBOT_MESSAGE_SETENDEFFECTORSUCTIONCUP_H

#include <ros/service_traits.h>


#include <dobot/SetEndEffectorSuctionCupRequest.h>
#include <dobot/SetEndEffectorSuctionCupResponse.h>


namespace dobot
{

struct SetEndEffectorSuctionCup
{

typedef SetEndEffectorSuctionCupRequest Request;
typedef SetEndEffectorSuctionCupResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetEndEffectorSuctionCup
} // namespace dobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot::SetEndEffectorSuctionCup > {
  static const char* value()
  {
    return "27763da58719d6c55997a5f535fcffda";
  }

  static const char* value(const ::dobot::SetEndEffectorSuctionCup&) { return value(); }
};

template<>
struct DataType< ::dobot::SetEndEffectorSuctionCup > {
  static const char* value()
  {
    return "dobot/SetEndEffectorSuctionCup";
  }

  static const char* value(const ::dobot::SetEndEffectorSuctionCup&) { return value(); }
};


// service_traits::MD5Sum< ::dobot::SetEndEffectorSuctionCupRequest> should match 
// service_traits::MD5Sum< ::dobot::SetEndEffectorSuctionCup > 
template<>
struct MD5Sum< ::dobot::SetEndEffectorSuctionCupRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::SetEndEffectorSuctionCup >::value();
  }
  static const char* value(const ::dobot::SetEndEffectorSuctionCupRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::SetEndEffectorSuctionCupRequest> should match 
// service_traits::DataType< ::dobot::SetEndEffectorSuctionCup > 
template<>
struct DataType< ::dobot::SetEndEffectorSuctionCupRequest>
{
  static const char* value()
  {
    return DataType< ::dobot::SetEndEffectorSuctionCup >::value();
  }
  static const char* value(const ::dobot::SetEndEffectorSuctionCupRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot::SetEndEffectorSuctionCupResponse> should match 
// service_traits::MD5Sum< ::dobot::SetEndEffectorSuctionCup > 
template<>
struct MD5Sum< ::dobot::SetEndEffectorSuctionCupResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::SetEndEffectorSuctionCup >::value();
  }
  static const char* value(const ::dobot::SetEndEffectorSuctionCupResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::SetEndEffectorSuctionCupResponse> should match 
// service_traits::DataType< ::dobot::SetEndEffectorSuctionCup > 
template<>
struct DataType< ::dobot::SetEndEffectorSuctionCupResponse>
{
  static const char* value()
  {
    return DataType< ::dobot::SetEndEffectorSuctionCup >::value();
  }
  static const char* value(const ::dobot::SetEndEffectorSuctionCupResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_MESSAGE_SETENDEFFECTORSUCTIONCUP_H
