// Generated by gencpp from file dobot/SetEMotor.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_SETEMOTOR_H
#define DOBOT_MESSAGE_SETEMOTOR_H

#include <ros/service_traits.h>


#include <dobot/SetEMotorRequest.h>
#include <dobot/SetEMotorResponse.h>


namespace dobot
{

struct SetEMotor
{

typedef SetEMotorRequest Request;
typedef SetEMotorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetEMotor
} // namespace dobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot::SetEMotor > {
  static const char* value()
  {
    return "a45df13761ba868c43b89ce505bf680a";
  }

  static const char* value(const ::dobot::SetEMotor&) { return value(); }
};

template<>
struct DataType< ::dobot::SetEMotor > {
  static const char* value()
  {
    return "dobot/SetEMotor";
  }

  static const char* value(const ::dobot::SetEMotor&) { return value(); }
};


// service_traits::MD5Sum< ::dobot::SetEMotorRequest> should match 
// service_traits::MD5Sum< ::dobot::SetEMotor > 
template<>
struct MD5Sum< ::dobot::SetEMotorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::SetEMotor >::value();
  }
  static const char* value(const ::dobot::SetEMotorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::SetEMotorRequest> should match 
// service_traits::DataType< ::dobot::SetEMotor > 
template<>
struct DataType< ::dobot::SetEMotorRequest>
{
  static const char* value()
  {
    return DataType< ::dobot::SetEMotor >::value();
  }
  static const char* value(const ::dobot::SetEMotorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot::SetEMotorResponse> should match 
// service_traits::MD5Sum< ::dobot::SetEMotor > 
template<>
struct MD5Sum< ::dobot::SetEMotorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::SetEMotor >::value();
  }
  static const char* value(const ::dobot::SetEMotorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::SetEMotorResponse> should match 
// service_traits::DataType< ::dobot::SetEMotor > 
template<>
struct DataType< ::dobot::SetEMotorResponse>
{
  static const char* value()
  {
    return DataType< ::dobot::SetEMotor >::value();
  }
  static const char* value(const ::dobot::SetEMotorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_MESSAGE_SETEMOTOR_H
