// Generated by gencpp from file dobot/SetHOMECmd.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_SETHOMECMD_H
#define DOBOT_MESSAGE_SETHOMECMD_H

#include <ros/service_traits.h>


#include <dobot/SetHOMECmdRequest.h>
#include <dobot/SetHOMECmdResponse.h>


namespace dobot
{

struct SetHOMECmd
{

typedef SetHOMECmdRequest Request;
typedef SetHOMECmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetHOMECmd
} // namespace dobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot::SetHOMECmd > {
  static const char* value()
  {
    return "cbf7b461449133eb5dd6ebbd8d38dedc";
  }

  static const char* value(const ::dobot::SetHOMECmd&) { return value(); }
};

template<>
struct DataType< ::dobot::SetHOMECmd > {
  static const char* value()
  {
    return "dobot/SetHOMECmd";
  }

  static const char* value(const ::dobot::SetHOMECmd&) { return value(); }
};


// service_traits::MD5Sum< ::dobot::SetHOMECmdRequest> should match 
// service_traits::MD5Sum< ::dobot::SetHOMECmd > 
template<>
struct MD5Sum< ::dobot::SetHOMECmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::SetHOMECmd >::value();
  }
  static const char* value(const ::dobot::SetHOMECmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::SetHOMECmdRequest> should match 
// service_traits::DataType< ::dobot::SetHOMECmd > 
template<>
struct DataType< ::dobot::SetHOMECmdRequest>
{
  static const char* value()
  {
    return DataType< ::dobot::SetHOMECmd >::value();
  }
  static const char* value(const ::dobot::SetHOMECmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot::SetHOMECmdResponse> should match 
// service_traits::MD5Sum< ::dobot::SetHOMECmd > 
template<>
struct MD5Sum< ::dobot::SetHOMECmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::SetHOMECmd >::value();
  }
  static const char* value(const ::dobot::SetHOMECmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::SetHOMECmdResponse> should match 
// service_traits::DataType< ::dobot::SetHOMECmd > 
template<>
struct DataType< ::dobot::SetHOMECmdResponse>
{
  static const char* value()
  {
    return DataType< ::dobot::SetHOMECmd >::value();
  }
  static const char* value(const ::dobot::SetHOMECmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_MESSAGE_SETHOMECMD_H
