// Generated by gencpp from file dobot/SetIOMultiplexing.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_SETIOMULTIPLEXING_H
#define DOBOT_MESSAGE_SETIOMULTIPLEXING_H

#include <ros/service_traits.h>


#include <dobot/SetIOMultiplexingRequest.h>
#include <dobot/SetIOMultiplexingResponse.h>


namespace dobot
{

struct SetIOMultiplexing
{

typedef SetIOMultiplexingRequest Request;
typedef SetIOMultiplexingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetIOMultiplexing
} // namespace dobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot::SetIOMultiplexing > {
  static const char* value()
  {
    return "0d42b2a07901322be1553ed3f1e55579";
  }

  static const char* value(const ::dobot::SetIOMultiplexing&) { return value(); }
};

template<>
struct DataType< ::dobot::SetIOMultiplexing > {
  static const char* value()
  {
    return "dobot/SetIOMultiplexing";
  }

  static const char* value(const ::dobot::SetIOMultiplexing&) { return value(); }
};


// service_traits::MD5Sum< ::dobot::SetIOMultiplexingRequest> should match 
// service_traits::MD5Sum< ::dobot::SetIOMultiplexing > 
template<>
struct MD5Sum< ::dobot::SetIOMultiplexingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::SetIOMultiplexing >::value();
  }
  static const char* value(const ::dobot::SetIOMultiplexingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::SetIOMultiplexingRequest> should match 
// service_traits::DataType< ::dobot::SetIOMultiplexing > 
template<>
struct DataType< ::dobot::SetIOMultiplexingRequest>
{
  static const char* value()
  {
    return DataType< ::dobot::SetIOMultiplexing >::value();
  }
  static const char* value(const ::dobot::SetIOMultiplexingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot::SetIOMultiplexingResponse> should match 
// service_traits::MD5Sum< ::dobot::SetIOMultiplexing > 
template<>
struct MD5Sum< ::dobot::SetIOMultiplexingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::SetIOMultiplexing >::value();
  }
  static const char* value(const ::dobot::SetIOMultiplexingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::SetIOMultiplexingResponse> should match 
// service_traits::DataType< ::dobot::SetIOMultiplexing > 
template<>
struct DataType< ::dobot::SetIOMultiplexingResponse>
{
  static const char* value()
  {
    return DataType< ::dobot::SetIOMultiplexing >::value();
  }
  static const char* value(const ::dobot::SetIOMultiplexingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_MESSAGE_SETIOMULTIPLEXING_H
