// Generated by gencpp from file dobot/SetJOGCoordinateParams.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_SETJOGCOORDINATEPARAMS_H
#define DOBOT_MESSAGE_SETJOGCOORDINATEPARAMS_H

#include <ros/service_traits.h>


#include <dobot/SetJOGCoordinateParamsRequest.h>
#include <dobot/SetJOGCoordinateParamsResponse.h>


namespace dobot
{

struct SetJOGCoordinateParams
{

typedef SetJOGCoordinateParamsRequest Request;
typedef SetJOGCoordinateParamsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetJOGCoordinateParams
} // namespace dobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot::SetJOGCoordinateParams > {
  static const char* value()
  {
    return "66026db026b6b1016fb4eccdf054b1ba";
  }

  static const char* value(const ::dobot::SetJOGCoordinateParams&) { return value(); }
};

template<>
struct DataType< ::dobot::SetJOGCoordinateParams > {
  static const char* value()
  {
    return "dobot/SetJOGCoordinateParams";
  }

  static const char* value(const ::dobot::SetJOGCoordinateParams&) { return value(); }
};


// service_traits::MD5Sum< ::dobot::SetJOGCoordinateParamsRequest> should match 
// service_traits::MD5Sum< ::dobot::SetJOGCoordinateParams > 
template<>
struct MD5Sum< ::dobot::SetJOGCoordinateParamsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::SetJOGCoordinateParams >::value();
  }
  static const char* value(const ::dobot::SetJOGCoordinateParamsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::SetJOGCoordinateParamsRequest> should match 
// service_traits::DataType< ::dobot::SetJOGCoordinateParams > 
template<>
struct DataType< ::dobot::SetJOGCoordinateParamsRequest>
{
  static const char* value()
  {
    return DataType< ::dobot::SetJOGCoordinateParams >::value();
  }
  static const char* value(const ::dobot::SetJOGCoordinateParamsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot::SetJOGCoordinateParamsResponse> should match 
// service_traits::MD5Sum< ::dobot::SetJOGCoordinateParams > 
template<>
struct MD5Sum< ::dobot::SetJOGCoordinateParamsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::SetJOGCoordinateParams >::value();
  }
  static const char* value(const ::dobot::SetJOGCoordinateParamsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::SetJOGCoordinateParamsResponse> should match 
// service_traits::DataType< ::dobot::SetJOGCoordinateParams > 
template<>
struct DataType< ::dobot::SetJOGCoordinateParamsResponse>
{
  static const char* value()
  {
    return DataType< ::dobot::SetJOGCoordinateParams >::value();
  }
  static const char* value(const ::dobot::SetJOGCoordinateParamsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_MESSAGE_SETJOGCOORDINATEPARAMS_H
