// Generated by gencpp from file dobot/SetJOGJointParams.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_SETJOGJOINTPARAMS_H
#define DOBOT_MESSAGE_SETJOGJOINTPARAMS_H

#include <ros/service_traits.h>


#include <dobot/SetJOGJointParamsRequest.h>
#include <dobot/SetJOGJointParamsResponse.h>


namespace dobot
{

struct SetJOGJointParams
{

typedef SetJOGJointParamsRequest Request;
typedef SetJOGJointParamsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetJOGJointParams
} // namespace dobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot::SetJOGJointParams > {
  static const char* value()
  {
    return "66026db026b6b1016fb4eccdf054b1ba";
  }

  static const char* value(const ::dobot::SetJOGJointParams&) { return value(); }
};

template<>
struct DataType< ::dobot::SetJOGJointParams > {
  static const char* value()
  {
    return "dobot/SetJOGJointParams";
  }

  static const char* value(const ::dobot::SetJOGJointParams&) { return value(); }
};


// service_traits::MD5Sum< ::dobot::SetJOGJointParamsRequest> should match 
// service_traits::MD5Sum< ::dobot::SetJOGJointParams > 
template<>
struct MD5Sum< ::dobot::SetJOGJointParamsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::SetJOGJointParams >::value();
  }
  static const char* value(const ::dobot::SetJOGJointParamsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::SetJOGJointParamsRequest> should match 
// service_traits::DataType< ::dobot::SetJOGJointParams > 
template<>
struct DataType< ::dobot::SetJOGJointParamsRequest>
{
  static const char* value()
  {
    return DataType< ::dobot::SetJOGJointParams >::value();
  }
  static const char* value(const ::dobot::SetJOGJointParamsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot::SetJOGJointParamsResponse> should match 
// service_traits::MD5Sum< ::dobot::SetJOGJointParams > 
template<>
struct MD5Sum< ::dobot::SetJOGJointParamsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::SetJOGJointParams >::value();
  }
  static const char* value(const ::dobot::SetJOGJointParamsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::SetJOGJointParamsResponse> should match 
// service_traits::DataType< ::dobot::SetJOGJointParams > 
template<>
struct DataType< ::dobot::SetJOGJointParamsResponse>
{
  static const char* value()
  {
    return DataType< ::dobot::SetJOGJointParams >::value();
  }
  static const char* value(const ::dobot::SetJOGJointParamsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_MESSAGE_SETJOGJOINTPARAMS_H
