// Generated by gencpp from file dobot/SetJOGCommonParams.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_SETJOGCOMMONPARAMS_H
#define DOBOT_MESSAGE_SETJOGCOMMONPARAMS_H

#include <ros/service_traits.h>


#include <dobot/SetJOGCommonParamsRequest.h>
#include <dobot/SetJOGCommonParamsResponse.h>


namespace dobot
{

struct SetJOGCommonParams
{

typedef SetJOGCommonParamsRequest Request;
typedef SetJOGCommonParamsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetJOGCommonParams
} // namespace dobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot::SetJOGCommonParams > {
  static const char* value()
  {
    return "07fac5c7832f03b11ac295e63e130ee0";
  }

  static const char* value(const ::dobot::SetJOGCommonParams&) { return value(); }
};

template<>
struct DataType< ::dobot::SetJOGCommonParams > {
  static const char* value()
  {
    return "dobot/SetJOGCommonParams";
  }

  static const char* value(const ::dobot::SetJOGCommonParams&) { return value(); }
};


// service_traits::MD5Sum< ::dobot::SetJOGCommonParamsRequest> should match 
// service_traits::MD5Sum< ::dobot::SetJOGCommonParams > 
template<>
struct MD5Sum< ::dobot::SetJOGCommonParamsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::SetJOGCommonParams >::value();
  }
  static const char* value(const ::dobot::SetJOGCommonParamsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::SetJOGCommonParamsRequest> should match 
// service_traits::DataType< ::dobot::SetJOGCommonParams > 
template<>
struct DataType< ::dobot::SetJOGCommonParamsRequest>
{
  static const char* value()
  {
    return DataType< ::dobot::SetJOGCommonParams >::value();
  }
  static const char* value(const ::dobot::SetJOGCommonParamsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot::SetJOGCommonParamsResponse> should match 
// service_traits::MD5Sum< ::dobot::SetJOGCommonParams > 
template<>
struct MD5Sum< ::dobot::SetJOGCommonParamsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::SetJOGCommonParams >::value();
  }
  static const char* value(const ::dobot::SetJOGCommonParamsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::SetJOGCommonParamsResponse> should match 
// service_traits::DataType< ::dobot::SetJOGCommonParams > 
template<>
struct DataType< ::dobot::SetJOGCommonParamsResponse>
{
  static const char* value()
  {
    return DataType< ::dobot::SetJOGCommonParams >::value();
  }
  static const char* value(const ::dobot::SetJOGCommonParamsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_MESSAGE_SETJOGCOMMONPARAMS_H
