// Generated by gencpp from file dobot/SetPTPJumpParams.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_SETPTPJUMPPARAMS_H
#define DOBOT_MESSAGE_SETPTPJUMPPARAMS_H

#include <ros/service_traits.h>


#include <dobot/SetPTPJumpParamsRequest.h>
#include <dobot/SetPTPJumpParamsResponse.h>


namespace dobot
{

struct SetPTPJumpParams
{

typedef SetPTPJumpParamsRequest Request;
typedef SetPTPJumpParamsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPTPJumpParams
} // namespace dobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot::SetPTPJumpParams > {
  static const char* value()
  {
    return "9264d5750a7f398bdbc1bbd16ec60e63";
  }

  static const char* value(const ::dobot::SetPTPJumpParams&) { return value(); }
};

template<>
struct DataType< ::dobot::SetPTPJumpParams > {
  static const char* value()
  {
    return "dobot/SetPTPJumpParams";
  }

  static const char* value(const ::dobot::SetPTPJumpParams&) { return value(); }
};


// service_traits::MD5Sum< ::dobot::SetPTPJumpParamsRequest> should match 
// service_traits::MD5Sum< ::dobot::SetPTPJumpParams > 
template<>
struct MD5Sum< ::dobot::SetPTPJumpParamsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::SetPTPJumpParams >::value();
  }
  static const char* value(const ::dobot::SetPTPJumpParamsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::SetPTPJumpParamsRequest> should match 
// service_traits::DataType< ::dobot::SetPTPJumpParams > 
template<>
struct DataType< ::dobot::SetPTPJumpParamsRequest>
{
  static const char* value()
  {
    return DataType< ::dobot::SetPTPJumpParams >::value();
  }
  static const char* value(const ::dobot::SetPTPJumpParamsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot::SetPTPJumpParamsResponse> should match 
// service_traits::MD5Sum< ::dobot::SetPTPJumpParams > 
template<>
struct MD5Sum< ::dobot::SetPTPJumpParamsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::SetPTPJumpParams >::value();
  }
  static const char* value(const ::dobot::SetPTPJumpParamsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::SetPTPJumpParamsResponse> should match 
// service_traits::DataType< ::dobot::SetPTPJumpParams > 
template<>
struct DataType< ::dobot::SetPTPJumpParamsResponse>
{
  static const char* value()
  {
    return DataType< ::dobot::SetPTPJumpParams >::value();
  }
  static const char* value(const ::dobot::SetPTPJumpParamsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_MESSAGE_SETPTPJUMPPARAMS_H
