// Generated by gencpp from file dobot/SetPTPCoordinateParams.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_SETPTPCOORDINATEPARAMS_H
#define DOBOT_MESSAGE_SETPTPCOORDINATEPARAMS_H

#include <ros/service_traits.h>


#include <dobot/SetPTPCoordinateParamsRequest.h>
#include <dobot/SetPTPCoordinateParamsResponse.h>


namespace dobot
{

struct SetPTPCoordinateParams
{

typedef SetPTPCoordinateParamsRequest Request;
typedef SetPTPCoordinateParamsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPTPCoordinateParams
} // namespace dobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot::SetPTPCoordinateParams > {
  static const char* value()
  {
    return "667693b23f3c212883d158fa88cec8f5";
  }

  static const char* value(const ::dobot::SetPTPCoordinateParams&) { return value(); }
};

template<>
struct DataType< ::dobot::SetPTPCoordinateParams > {
  static const char* value()
  {
    return "dobot/SetPTPCoordinateParams";
  }

  static const char* value(const ::dobot::SetPTPCoordinateParams&) { return value(); }
};


// service_traits::MD5Sum< ::dobot::SetPTPCoordinateParamsRequest> should match 
// service_traits::MD5Sum< ::dobot::SetPTPCoordinateParams > 
template<>
struct MD5Sum< ::dobot::SetPTPCoordinateParamsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::SetPTPCoordinateParams >::value();
  }
  static const char* value(const ::dobot::SetPTPCoordinateParamsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::SetPTPCoordinateParamsRequest> should match 
// service_traits::DataType< ::dobot::SetPTPCoordinateParams > 
template<>
struct DataType< ::dobot::SetPTPCoordinateParamsRequest>
{
  static const char* value()
  {
    return DataType< ::dobot::SetPTPCoordinateParams >::value();
  }
  static const char* value(const ::dobot::SetPTPCoordinateParamsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot::SetPTPCoordinateParamsResponse> should match 
// service_traits::MD5Sum< ::dobot::SetPTPCoordinateParams > 
template<>
struct MD5Sum< ::dobot::SetPTPCoordinateParamsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::SetPTPCoordinateParams >::value();
  }
  static const char* value(const ::dobot::SetPTPCoordinateParamsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::SetPTPCoordinateParamsResponse> should match 
// service_traits::DataType< ::dobot::SetPTPCoordinateParams > 
template<>
struct DataType< ::dobot::SetPTPCoordinateParamsResponse>
{
  static const char* value()
  {
    return DataType< ::dobot::SetPTPCoordinateParams >::value();
  }
  static const char* value(const ::dobot::SetPTPCoordinateParamsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_MESSAGE_SETPTPCOORDINATEPARAMS_H
