// Generated by gencpp from file dobot/SetPTPCmdRequest.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_SETPTPCMDREQUEST_H
#define DOBOT_MESSAGE_SETPTPCMDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot
{
template <class ContainerAllocator>
struct SetPTPCmdRequest_
{
  typedef SetPTPCmdRequest_<ContainerAllocator> Type;

  SetPTPCmdRequest_()
    : ptpMode(0)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , r(0.0)  {
    }
  SetPTPCmdRequest_(const ContainerAllocator& _alloc)
    : ptpMode(0)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , r(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _ptpMode_type;
  _ptpMode_type ptpMode;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _r_type;
  _r_type r;




  typedef boost::shared_ptr< ::dobot::SetPTPCmdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot::SetPTPCmdRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetPTPCmdRequest_

typedef ::dobot::SetPTPCmdRequest_<std::allocator<void> > SetPTPCmdRequest;

typedef boost::shared_ptr< ::dobot::SetPTPCmdRequest > SetPTPCmdRequestPtr;
typedef boost::shared_ptr< ::dobot::SetPTPCmdRequest const> SetPTPCmdRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot::SetPTPCmdRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot::SetPTPCmdRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dobot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'dobot': ['/home/qch/dobot_ws/src/dobot/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dobot::SetPTPCmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot::SetPTPCmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::SetPTPCmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::SetPTPCmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::SetPTPCmdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::SetPTPCmdRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot::SetPTPCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fb740859230cd62a75096d59fd085a9e";
  }

  static const char* value(const ::dobot::SetPTPCmdRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfb740859230cd62aULL;
  static const uint64_t static_value2 = 0x75096d59fd085a9eULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot::SetPTPCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot/SetPTPCmdRequest";
  }

  static const char* value(const ::dobot::SetPTPCmdRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot::SetPTPCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 ptpMode\n\
float32 x\n\
float32 y\n\
float32 z\n\
float32 r\n\
";
  }

  static const char* value(const ::dobot::SetPTPCmdRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot::SetPTPCmdRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ptpMode);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.r);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetPTPCmdRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot::SetPTPCmdRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot::SetPTPCmdRequest_<ContainerAllocator>& v)
  {
    s << indent << "ptpMode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ptpMode);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "r: ";
    Printer<float>::stream(s, indent + "  ", v.r);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_MESSAGE_SETPTPCMDREQUEST_H
