// Generated by gencpp from file dobot/SetPTPCommonParams.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_SETPTPCOMMONPARAMS_H
#define DOBOT_MESSAGE_SETPTPCOMMONPARAMS_H

#include <ros/service_traits.h>


#include <dobot/SetPTPCommonParamsRequest.h>
#include <dobot/SetPTPCommonParamsResponse.h>


namespace dobot
{

struct SetPTPCommonParams
{

typedef SetPTPCommonParamsRequest Request;
typedef SetPTPCommonParamsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPTPCommonParams
} // namespace dobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot::SetPTPCommonParams > {
  static const char* value()
  {
    return "07fac5c7832f03b11ac295e63e130ee0";
  }

  static const char* value(const ::dobot::SetPTPCommonParams&) { return value(); }
};

template<>
struct DataType< ::dobot::SetPTPCommonParams > {
  static const char* value()
  {
    return "dobot/SetPTPCommonParams";
  }

  static const char* value(const ::dobot::SetPTPCommonParams&) { return value(); }
};


// service_traits::MD5Sum< ::dobot::SetPTPCommonParamsRequest> should match 
// service_traits::MD5Sum< ::dobot::SetPTPCommonParams > 
template<>
struct MD5Sum< ::dobot::SetPTPCommonParamsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::SetPTPCommonParams >::value();
  }
  static const char* value(const ::dobot::SetPTPCommonParamsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::SetPTPCommonParamsRequest> should match 
// service_traits::DataType< ::dobot::SetPTPCommonParams > 
template<>
struct DataType< ::dobot::SetPTPCommonParamsRequest>
{
  static const char* value()
  {
    return DataType< ::dobot::SetPTPCommonParams >::value();
  }
  static const char* value(const ::dobot::SetPTPCommonParamsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot::SetPTPCommonParamsResponse> should match 
// service_traits::MD5Sum< ::dobot::SetPTPCommonParams > 
template<>
struct MD5Sum< ::dobot::SetPTPCommonParamsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::SetPTPCommonParams >::value();
  }
  static const char* value(const ::dobot::SetPTPCommonParamsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::SetPTPCommonParamsResponse> should match 
// service_traits::DataType< ::dobot::SetPTPCommonParams > 
template<>
struct DataType< ::dobot::SetPTPCommonParamsResponse>
{
  static const char* value()
  {
    return DataType< ::dobot::SetPTPCommonParams >::value();
  }
  static const char* value(const ::dobot::SetPTPCommonParamsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_MESSAGE_SETPTPCOMMONPARAMS_H
