// Generated by gencpp from file dobot/SetPTPJointParams.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_SETPTPJOINTPARAMS_H
#define DOBOT_MESSAGE_SETPTPJOINTPARAMS_H

#include <ros/service_traits.h>


#include <dobot/SetPTPJointParamsRequest.h>
#include <dobot/SetPTPJointParamsResponse.h>


namespace dobot
{

struct SetPTPJointParams
{

typedef SetPTPJointParamsRequest Request;
typedef SetPTPJointParamsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPTPJointParams
} // namespace dobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot::SetPTPJointParams > {
  static const char* value()
  {
    return "66026db026b6b1016fb4eccdf054b1ba";
  }

  static const char* value(const ::dobot::SetPTPJointParams&) { return value(); }
};

template<>
struct DataType< ::dobot::SetPTPJointParams > {
  static const char* value()
  {
    return "dobot/SetPTPJointParams";
  }

  static const char* value(const ::dobot::SetPTPJointParams&) { return value(); }
};


// service_traits::MD5Sum< ::dobot::SetPTPJointParamsRequest> should match 
// service_traits::MD5Sum< ::dobot::SetPTPJointParams > 
template<>
struct MD5Sum< ::dobot::SetPTPJointParamsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::SetPTPJointParams >::value();
  }
  static const char* value(const ::dobot::SetPTPJointParamsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::SetPTPJointParamsRequest> should match 
// service_traits::DataType< ::dobot::SetPTPJointParams > 
template<>
struct DataType< ::dobot::SetPTPJointParamsRequest>
{
  static const char* value()
  {
    return DataType< ::dobot::SetPTPJointParams >::value();
  }
  static const char* value(const ::dobot::SetPTPJointParamsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot::SetPTPJointParamsResponse> should match 
// service_traits::MD5Sum< ::dobot::SetPTPJointParams > 
template<>
struct MD5Sum< ::dobot::SetPTPJointParamsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::SetPTPJointParams >::value();
  }
  static const char* value(const ::dobot::SetPTPJointParamsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::SetPTPJointParamsResponse> should match 
// service_traits::DataType< ::dobot::SetPTPJointParams > 
template<>
struct DataType< ::dobot::SetPTPJointParamsResponse>
{
  static const char* value()
  {
    return DataType< ::dobot::SetPTPJointParams >::value();
  }
  static const char* value(const ::dobot::SetPTPJointParamsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_MESSAGE_SETPTPJOINTPARAMS_H
